[project]
name = "ipynb-tui-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.31.0",
    "ipython>=8.18.1",
    "nbformat>=5.10.4",
    "textual>=6.6.0",
]
